apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight
  template:
    metadata:
      labels:
        app: flight
    spec:
      containers:
        - image: northamerica-northeast2-docker.pkg.dev/buoyant-history-415921/sofe3980u/flight
          name: flight
          ports:
            - containerPort: 8080
              name: flight